In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [60]:
data = pd.read_csv("./Dataset/BanksDataset/AXISBANK.csv")
data.head(10)

Date   Symbol Series  Prev Close   Open   High    Low  Last  Close  \
0  2000-01-03  UTIBANK     EQ       24.70  26.70  26.70  26.70  26.7  26.70   
1  2000-01-04  UTIBANK     EQ       26.70  27.00  28.70  26.50  27.0  26.85   
2  2000-01-05  UTIBANK     EQ       26.85  26.00  27.75  25.50  26.4  26.30   
3  2000-01-06  UTIBANK     EQ       26.30  25.80  27.00  25.80  25.9  25.95   
4  2000-01-07  UTIBANK     EQ       25.95  25.00  26.00  24.25  25.0  24.80   
5  2000-01-10  UTIBANK     EQ       24.80  25.05  26.50  25.00  25.0  25.00   
6  2000-01-11  UTIBANK     EQ       25.00  24.25  24.80  23.00  23.0  23.20   
7  2000-01-12  UTIBANK     EQ       23.20  22.60  24.50  22.60  24.0  24.00   
8  2000-01-13  UTIBANK     EQ       24.00  24.50  24.50  23.10  23.8  23.60   
9  2000-01-14  UTIBANK     EQ       23.60  24.00  24.20  22.50  23.5  23.25   

    VWAP  Volume      Turnover  Trades  Deliverable Volume  %Deliverble  
0  26.70  112100  2.993070e+11     NaN                 NaN          NaN  
1  27.24  234500  6.387275e+11     NaN                 NaN          NaN  
2  26.24  170100  4.462980e+11     NaN                 NaN          NaN  
3  26.27  102100  2.681730e+11     NaN                 NaN          NaN  
4  25.04   62600  1.567220e+11     NaN                 NaN          NaN  
5  25.29   64200  1.623340e+11     NaN                 NaN          NaN  
6  23.90   91700  2.191725e+11     NaN                 NaN          NaN  
7  23.97   32500  7.791350e+10     NaN                 NaN          NaN  
8  23.77   48300  1.147955e+11     NaN                 NaN          NaN  
9  23.17   30700  7.114250e+10     NaN                 NaN          NaN

In [61]:
data = data.drop(["Series","Trades","Deliverable Volume","%Deliverble", "Turnover"], axis= 1)

In [43]:
print(data)
value = data.values 

Date    Symbol  Prev Close   Open    High     Low   Last   Close  \
0     2000-01-03   UTIBANK       24.70   26.7   26.70   26.70   26.7   26.70   
1     2000-01-04   UTIBANK       26.70   27.0   28.70   26.50   27.0   26.85   
2     2000-01-05   UTIBANK       26.85   26.0   27.75   25.50   26.4   26.30   
3     2000-01-06   UTIBANK       26.30   25.8   27.00   25.80   25.9   25.95   
4     2000-01-07   UTIBANK       25.95   25.0   26.00   24.25   25.0   24.80   
...          ...       ...         ...    ...     ...     ...    ...     ...   
5092  2020-06-24  AXISBANK      443.65  448.0  448.50  422.20  425.4  424.65   
5093  2020-06-25  AXISBANK      424.65  419.0  428.70  410.35  418.9  421.70   
5094  2020-06-26  AXISBANK      421.70  426.0  428.75  418.00  426.0  424.85   
5095  2020-06-29  AXISBANK      424.85  415.0  415.80  402.35  404.9  404.80   
5096  2020-06-30  AXISBANK      404.80  410.0  414.80  404.05  407.3  406.65   

        VWAP    Volume      Turnover  
0      26.70

In [87]:
X = value[:, 2:7]
X_ = value[:,8:]
y = value[:, 7]
x = np.concatenate((X,X_), axis = 1)

[26.7 26.85 26.3 ... 424.85 404.8 406.65]
[[24.7 26.7 26.7 ... 26.7 112100 299307000000.0]
 [26.7 27.0 28.7 ... 27.24 234500 638727500000.0]
 [26.85 26.0 27.75 ... 26.24 170100 446298000000.0]
 ...
 [421.7 426.0 428.75 ... 422.8 32611425 1378814835820000.0]
 [424.85 415.0 415.8 ... 406.79 36320111 1477447751155000.0]
 [404.8 410.0 414.8 ... 409.15 26951992 1102743626475000.0]]


In [89]:
from sklearn.model_selection import train_test_split

In [103]:
 X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.5,)
 print(len(y_train))

2548


In [107]:
plt.figure(figsize=(500,500))
plt.plot(y_train, label='Close Price history')

In [100]:
ones = np.ones((X_train.shape[0],1))
X_train = np.hstack((ones,X_train))
print(X_train.shape)

(2548, 9)


In [98]:
def hypothesis(X,theta):
    return np.dot(X,theta)

def error(X,y,theta):
    m = X.shape[0]
    y_ = hypothesis(X,theta)
    e = np.sum((y - y_)**2)
    return e/m


def gradient(X,y,theta):
    m = X.shape[0]
    y_ = hypothesis(X,theta)
    grad = np.dot(X.T,(y_ - y))            
    return grad/m

def gradientDescent(X,y,learning_rate = 0.1, max_epoch = 300):
    n = X.shape[1]
    theta = np.zeros((n,))
    error_list = []
    for i in range(max_epoch):
        e = error(X,y,theta)
        error_list.append(e)
        grad = gradient(X,y,theta)
        theta = theta - learning_rate*grad
            
    return theta,error_list

OverflowError: (34, 'Result too large')